version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
